# Generated by Django 5.2.5 on 2026-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='g', help_text='e.g., g, mg, ml, piece, capsule', max_length=20),
        ),
    ]
